---
- name: Install Glance packages
  apt:
    name: glance
    state: present

- name: Configure Glance API
  blockinfile:
    dest: /etc/glance/glance-api.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Glance API Configuration"
    block: |
      [database]
      connection = mysql+pymysql://glance:GLANCE_DBPASS@localhost/glance

      [keystone_authtoken]
      www_authenticate_uri  = http://localhost:5000
      auth_url = http://localhost:5000
      memcached_servers = localhost:11211
      auth_type = password
      project_domain_name = Default
      user_domain_name = Default
      project_name = service
      username = glance
      password = GLANCE_PASS

      [paste_deploy]
      flavor = keystone

      [glance_store]
      enabled_backends=fs:file
      default_backend = fs

      [fs]
      filesystem_store_datadir = /var/lib/glance/images/

      [oslo_limit]
      auth_url = http://controller:5000
      auth_type = password
      user_domain_id = default
      username = glance
      system_scope = all
      password = GLANCE_PASS
      endpoint_id = 340be3625e9b4239a6415d034e98aace
      region_name = RegionOne

      [DEFAULT]
      use_keystone_limits = True
  vars:
    GLANCE_DBPASS: "GLANCE"
    GLANCE_PASS: "GLANCE_PASS"

- name: Add Glance user to system-scope reader role
  shell: >
    env OS_USERNAME=admin OS_PASSWORD=ADMIN_PASS OS_PROJECT_NAME=admin OS_AUTH_URL=http://localhost:5000/v3 OS_IDENTITY_API_VERSION=3 openstack role add --user glance --user-domain Default --system all reader

- name: Populate the Image service database
  become: true
  shell: glance-manage db_sync

- name: Restart Glance API service
  service:
    name: glance-api
    state: restarted
